export const BLE_SERVICE_UUID = "YOUR-SERVICE-UUID";

export const BLE_CHARACTERISTICS = {
  ECG: "YOUR-ECG-CHARACTERISTIC-UUID",
  VITALS: "YOUR-VITALS-CHARACTERISTIC-UUID",
  BATTERY: "YOUR-BATTERY-CHARACTERISTIC-UUID",
};